#!/bin/bash

ANDROID_BUILD_TOP="$(dirname $(realpath "$0"))"
CHECK="$(echo $1 | grep -q check && echo 1)"
GERRIT_USERNAME="$(git config review.review.lineageos.org.username)"

function repopick() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "${@: -1} - " ; ssh lineage-gerrit gerrit query ${@: -1} --format=JSON | jq --slurp -r '.[0].status'
    else
        ${ANDROID_BUILD_TOP}/vendor/lineage/build/tools/repopick.py \
            -g "ssh://$GERRIT_USERNAME@review.lineageos.org:29418" $@
    fi
}

function repopickchain() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "$1 - " ; ssh lineage-gerrit gerrit query $1 --format=JSON | jq --slurp -r '.[0].status'
    else
        `${ANDROID_BUILD_TOP}/gen_chain $@`
    fi
}

function rc() {
    echo `${ANDROID_BUILD_TOP}/gen_chain $@ | cut -b10-`
}

#
# _examples_
#
# # repo/1
# changes=(
#     2137 # hello
#     `rc 2137` # hello (chain)
# )
# repopick ${changes[@]}
#
# # repo/2
# repopickchain 2137 # hello (chain)
#
# # repo/3
# repopick 2137 # hello
#

# scripts
repopick 460695 # device-deps-regenerator: Add lineage-23.1 branch

# frameworks/base
repopickchain 462453 # SystemUI: fix the tiles editor

# packages/apps/Launcher3
repopickchain 460880 # Launcher3: Fix Taskbar{Model,View}CallbacksFactory instantiation

# packages/apps/Settings
repopickchain 462603 # fixup! Settings: Network setup UI changes for SUW

wait
